name: efficials_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.2.1
  shared_preferences: ^2.3.3
  intl: ^0.20.2
  table_calendar: ^3.2.0
  font_awesome_flutter: ^10.7.0
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.2
  path: ^1.8.3
  path_provider: ^2.1.1
  crypto: ^3.0.3
  url_launcher: ^6.1.12
  permission_handler: ^11.0.1
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_messaging: ^15.1.3
  excel: ^4.0.6
  file_picker: ^8.1.2
  share_plus: ^10.1.0
  # Debugging and Analytics
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true