name: efficials_app
description: A new Flutter project.
publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'  # Specifies compatible Dart SDK versions

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2  # For iOS-style icons
  http: ^1.2.1  # For making HTTP requests (e.g., API calls)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0  # For code linting (optional but recommended)

flutter:
  uses-material-design: true  # Enables Material Design components

  # Uncomment and configure the following if your app uses assets or fonts
  # assets:
  #   - images/logo.png
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf