// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQpfHNCkfQWfhKoWsaC9SVNS8awKVq1OE',
    appId: '1:907190154709:web:a18d04881c49063ff7f95c',
    messagingSenderId: '907190154709',
    projectId: 'efficials-app',
    authDomain: 'efficials-app.firebaseapp.com',
    storageBucket: 'efficials-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwLWks45QutyGtJx2DqXuTLa4_8w-4G-A',
    appId: '1:907190154709:android:d06353dd57ea575ff7f95c',
    messagingSenderId: '907190154709',
    projectId: 'efficials-app',
    storageBucket: 'efficials-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6H6UmumwdTR-dHftfeymsapl4UDN-vkA',
    appId: '1:907190154709:ios:22d9971cdef82981f7f95c',
    messagingSenderId: '907190154709',
    projectId: 'efficials-app',
    storageBucket: 'efficials-app.firebasestorage.app',
    iosBundleId: 'com.example.efficialsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDummyKey_Replace_With_Real_Key',
    appId: '1:123456789:macos:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'efficials-app-test',
    storageBucket: 'efficials-app-test.appspot.com',
    iosBundleId: 'com.example.efficialsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQpfHNCkfQWfhKoWsaC9SVNS8awKVq1OE',
    appId: '1:907190154709:web:d5bf1769d81eb731f7f95c',
    messagingSenderId: '907190154709',
    projectId: 'efficials-app',
    authDomain: 'efficials-app.firebaseapp.com',
    storageBucket: 'efficials-app.firebasestorage.app',
  );

}